# Generated by Django 4.2.2 on 2023-07-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BroadcastNotification',
            new_name='Notification',
        ),
    ]
